Fix clang-tidy issue
generated/src/aws-cpp-sdk-s3/include/aws/s3/model/AbortMultipartUploadResult.h:25:7: error: Value assigned to field 'm_HttpResponseCode' in implicit constructor is uninitialized [clang-analyzer-core.uninitialized.Assign,-warnings-as-errors]
   25 | class AbortMultipartUploadResult {
      |       ^
/ClickHouse/src/IO/tests/gtest_writebuffer_s3.cpp:402:9: note: Taking false branch
  402 |         if (injections)
      |         ^
/ClickHouse/src/IO/tests/gtest_writebuffer_s3.cpp:414:16: note: Calling constructor for 'Outcome<Aws::S3::Model::AbortMultipartUploadResult, Aws::S3::S3Error>'
  414 |         return Aws::S3::Model::AbortMultipartUploadOutcome(result);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/ClickHouse/contrib/aws/src/aws-cpp-sdk-core/include/aws/core/utils/Outcome.h:34:35: note: Calling implicit copy constructor for 'AbortMultipartUploadResult'
   34 |             Outcome(const R& r) : result(r), error(), success(true)
      |                                   ^~~~~~~~~
/ClickHouse/contrib/aws/generated/src/aws-cpp-sdk-s3/include/aws/s3/model/AbortMultipartUploadResult.h:25:7: note: Value assigned to field 'm_HttpResponseCode' in implicit constructor is uninitialized
   25 | class AbortMultipartUploadResult {
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~

(cherry picked from commit 22f694afbdc7e9766894998c3745e23f004f8b86)